/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiConfirmRouteImport } from './routes/api/confirm'
import { Route as ApiExecuteRouteImport } from './routes/api/execute'
import { Route as ApiExecuteStreamRouteImport } from './routes/api/execute-stream'
import { Route as ApiMossHealthRouteImport } from './routes/api/moss-health'
import { Route as ApiProposeRouteImport } from './routes/api/propose'
import { Route as ApiProposeStreamRouteImport } from './routes/api/propose-stream'
import { Route as ApiRunRouteImport } from './routes/api/run'
import { Route as ApiScenariosRouteImport } from './routes/api/scenarios'
import { Route as ApiWalletHandoffRouteImport } from './routes/api/wallet-handoff'
import { Route as ApiFixtureScenarioIdRouteImport } from './routes/api/fixture.$scenarioId'
import { Route as ApiRawEvidenceReportIdRouteImport } from './routes/api/raw-evidence.$reportId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConfirmRoute = ApiConfirmRouteImport.update({
  id: '/api/confirm',
  path: '/api/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExecuteRoute = ApiExecuteRouteImport.update({
  id: '/api/execute',
  path: '/api/execute',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExecuteStreamRoute = ApiExecuteStreamRouteImport.update({
  id: '/api/execute-stream',
  path: '/api/execute-stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMossHealthRoute = ApiMossHealthRouteImport.update({
  id: '/api/moss-health',
  path: '/api/moss-health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProposeRoute = ApiProposeRouteImport.update({
  id: '/api/propose',
  path: '/api/propose',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProposeStreamRoute = ApiProposeStreamRouteImport.update({
  id: '/api/propose-stream',
  path: '/api/propose-stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRunRoute = ApiRunRouteImport.update({
  id: '/api/run',
  path: '/api/run',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScenariosRoute = ApiScenariosRouteImport.update({
  id: '/api/scenarios',
  path: '/api/scenarios',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWalletHandoffRoute = ApiWalletHandoffRouteImport.update({
  id: '/api/wallet-handoff',
  path: '/api/wallet-handoff',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFixtureScenarioIdRoute = ApiFixtureScenarioIdRouteImport.update({
  id: '/api/fixture/$scenarioId',
  path: '/api/fixture/$scenarioId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRawEvidenceReportIdRoute = ApiRawEvidenceReportIdRouteImport.update({
  id: '/api/raw-evidence/$reportId',
  path: '/api/raw-evidence/$reportId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/confirm': typeof ApiConfirmRoute
  '/api/execute': typeof ApiExecuteRoute
  '/api/execute-stream': typeof ApiExecuteStreamRoute
  '/api/moss-health': typeof ApiMossHealthRoute
  '/api/propose': typeof ApiProposeRoute
  '/api/propose-stream': typeof ApiProposeStreamRoute
  '/api/run': typeof ApiRunRoute
  '/api/scenarios': typeof ApiScenariosRoute
  '/api/wallet-handoff': typeof ApiWalletHandoffRoute
  '/api/fixture/$scenarioId': typeof ApiFixtureScenarioIdRoute
  '/api/raw-evidence/$reportId': typeof ApiRawEvidenceReportIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/confirm': typeof ApiConfirmRoute
  '/api/execute': typeof ApiExecuteRoute
  '/api/execute-stream': typeof ApiExecuteStreamRoute
  '/api/moss-health': typeof ApiMossHealthRoute
  '/api/propose': typeof ApiProposeRoute
  '/api/propose-stream': typeof ApiProposeStreamRoute
  '/api/run': typeof ApiRunRoute
  '/api/scenarios': typeof ApiScenariosRoute
  '/api/wallet-handoff': typeof ApiWalletHandoffRoute
  '/api/fixture/$scenarioId': typeof ApiFixtureScenarioIdRoute
  '/api/raw-evidence/$reportId': typeof ApiRawEvidenceReportIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/confirm': typeof ApiConfirmRoute
  '/api/execute': typeof ApiExecuteRoute
  '/api/execute-stream': typeof ApiExecuteStreamRoute
  '/api/moss-health': typeof ApiMossHealthRoute
  '/api/propose': typeof ApiProposeRoute
  '/api/propose-stream': typeof ApiProposeStreamRoute
  '/api/run': typeof ApiRunRoute
  '/api/scenarios': typeof ApiScenariosRoute
  '/api/wallet-handoff': typeof ApiWalletHandoffRoute
  '/api/fixture/$scenarioId': typeof ApiFixtureScenarioIdRoute
  '/api/raw-evidence/$reportId': typeof ApiRawEvidenceReportIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/chat'
    | '/api/confirm'
    | '/api/execute'
    | '/api/execute-stream'
    | '/api/moss-health'
    | '/api/propose'
    | '/api/propose-stream'
    | '/api/run'
    | '/api/scenarios'
    | '/api/wallet-handoff'
    | '/api/fixture/$scenarioId'
    | '/api/raw-evidence/$reportId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/chat'
    | '/api/confirm'
    | '/api/execute'
    | '/api/execute-stream'
    | '/api/moss-health'
    | '/api/propose'
    | '/api/propose-stream'
    | '/api/run'
    | '/api/scenarios'
    | '/api/wallet-handoff'
    | '/api/fixture/$scenarioId'
    | '/api/raw-evidence/$reportId'
  id:
    | '__root__'
    | '/'
    | '/api/chat'
    | '/api/confirm'
    | '/api/execute'
    | '/api/execute-stream'
    | '/api/moss-health'
    | '/api/propose'
    | '/api/propose-stream'
    | '/api/run'
    | '/api/scenarios'
    | '/api/wallet-handoff'
    | '/api/fixture/$scenarioId'
    | '/api/raw-evidence/$reportId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiConfirmRoute: typeof ApiConfirmRoute
  ApiExecuteRoute: typeof ApiExecuteRoute
  ApiExecuteStreamRoute: typeof ApiExecuteStreamRoute
  ApiMossHealthRoute: typeof ApiMossHealthRoute
  ApiProposeRoute: typeof ApiProposeRoute
  ApiProposeStreamRoute: typeof ApiProposeStreamRoute
  ApiRunRoute: typeof ApiRunRoute
  ApiScenariosRoute: typeof ApiScenariosRoute
  ApiWalletHandoffRoute: typeof ApiWalletHandoffRoute
  ApiFixtureScenarioIdRoute: typeof ApiFixtureScenarioIdRoute
  ApiRawEvidenceReportIdRoute: typeof ApiRawEvidenceReportIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/confirm': {
      id: '/api/confirm'
      path: '/api/confirm'
      fullPath: '/api/confirm'
      preLoaderRoute: typeof ApiConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/execute': {
      id: '/api/execute'
      path: '/api/execute'
      fullPath: '/api/execute'
      preLoaderRoute: typeof ApiExecuteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/execute-stream': {
      id: '/api/execute-stream'
      path: '/api/execute-stream'
      fullPath: '/api/execute-stream'
      preLoaderRoute: typeof ApiExecuteStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/moss-health': {
      id: '/api/moss-health'
      path: '/api/moss-health'
      fullPath: '/api/moss-health'
      preLoaderRoute: typeof ApiMossHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/propose': {
      id: '/api/propose'
      path: '/api/propose'
      fullPath: '/api/propose'
      preLoaderRoute: typeof ApiProposeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/propose-stream': {
      id: '/api/propose-stream'
      path: '/api/propose-stream'
      fullPath: '/api/propose-stream'
      preLoaderRoute: typeof ApiProposeStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/run': {
      id: '/api/run'
      path: '/api/run'
      fullPath: '/api/run'
      preLoaderRoute: typeof ApiRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scenarios': {
      id: '/api/scenarios'
      path: '/api/scenarios'
      fullPath: '/api/scenarios'
      preLoaderRoute: typeof ApiScenariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wallet-handoff': {
      id: '/api/wallet-handoff'
      path: '/api/wallet-handoff'
      fullPath: '/api/wallet-handoff'
      preLoaderRoute: typeof ApiWalletHandoffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fixture/$scenarioId': {
      id: '/api/fixture/$scenarioId'
      path: '/api/fixture/$scenarioId'
      fullPath: '/api/fixture/$scenarioId'
      preLoaderRoute: typeof ApiFixtureScenarioIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/raw-evidence/$reportId': {
      id: '/api/raw-evidence/$reportId'
      path: '/api/raw-evidence/$reportId'
      fullPath: '/api/raw-evidence/$reportId'
      preLoaderRoute: typeof ApiRawEvidenceReportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiChatRoute: ApiChatRoute,
  ApiConfirmRoute: ApiConfirmRoute,
  ApiExecuteRoute: ApiExecuteRoute,
  ApiExecuteStreamRoute: ApiExecuteStreamRoute,
  ApiMossHealthRoute: ApiMossHealthRoute,
  ApiProposeRoute: ApiProposeRoute,
  ApiProposeStreamRoute: ApiProposeStreamRoute,
  ApiRunRoute: ApiRunRoute,
  ApiScenariosRoute: ApiScenariosRoute,
  ApiWalletHandoffRoute: ApiWalletHandoffRoute,
  ApiFixtureScenarioIdRoute: ApiFixtureScenarioIdRoute,
  ApiRawEvidenceReportIdRoute: ApiRawEvidenceReportIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
